#!/usr/bin/perl

use strict;

print("Not really running anything ...\n");
print("This will fail, pass or tmpfail randomly.\n");

my $rand = int(rand(10));

if ($rand <= 7) {
  print("Passed :-)\n");
  exit(0);
} elsif ($rand <= 8.5) {
  print("Failed :-(\n");
  exit(4);
} else {
  print("Some error ocurred");
  exit 16;
}


