#!/bin/sh

set -eu

usage() {
  cat <<EOF
usage: backends/lxc/test-package [OPTIONS] PACKAGE OUTPUTDIR [EXTRA-AUTOPKGTEST-ARGS]

$@
EOF
}

container_name=$(date +ci-%s)

debci-autopkgtest --user debci --apt-upgrade "$@" \
  -- lxc --sudo --name "${container_name}" "autopkgtest-${debci_suite}-${debci_arch}"
