#!/bin/sh

set -eu

usage() {
  cat <<EOF
usage: backends/lxc/test-package [OPTIONS] PACKAGE OUTPUTDIR [EXTRA-AUTOPKGTEST-ARGS]

$@
EOF
}

# container name has to be 15 characters or less. see
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898875
container_name=ci-$(date +%j)-$(openssl rand -hex 4)

debci-autopkgtest --user debci --apt-upgrade "$@" \
  -- lxc --sudo --name "${container_name}" "autopkgtest-${debci_suite}-${debci_arch}"
