#!/bin/sh

set -eu

usage() {
  cat <<EOF
usage: backends/lxc/test-package [OPTIONS] PACKAGE OUTPUTDIR

$@
EOF
}

base=$(readlink -f $(dirname $(readlink -f $0))/../..)
. $base/lib/environment.sh
. $base/lib/functions.sh

prepare_args

if [ $# -ne 2 ]; then
  usage
  exit 1
fi
package="$1"
outdir="$2"

# see create-testbed
[ $debci_suite = unstable ] && debci_suite=sid

container_name=$(basename ${package})-$(date +%s)

rc=0
adt-run --user debci --output-dir "$outdir" "$package" --apt-upgrade --- lxc --sudo --name ${container_name} adt-${debci_suite}-${debci_arch} || rc=$?

echo $rc > "$outdir/exitcode"
exit $rc
