#!/bin/sh

set -e

base=$(readlink -f $(dirname $(readlink -f $0))/../..)
. $base/lib/environment.sh

schroot \
  --chroot "$debci_chroot_name" \
  --directory / \
  -- dpkg-query --show | awk '{ print($1, $2) }'
