#!/bin/sh

set -e

usage() {
  cat <<EOF
usage: backends/schroot/test-package [OPTIONS] PACKAGE

$@
EOF
}

base=$(readlink -f $(dirname $(readlink -f $0))/../..)
. $base/lib/environment.sh
. $base/lib/functions.sh

prepare_args

if [ $# -ne 1 ]; then
  usage
  exit 1
fi
package="$1"

tmpdir=$(mktemp -d)
cleanup() {
  if [ -d "$tmpdir" ]; then
    rm -rf "$tmpdir"
  fi
}
trap cleanup INT TERM EXIT

adt-run "$package" --- adt-virt-schroot "${debci_chroot_name}"
