#!/bin/sh

set -eu

usage() {
  cat <<EOF
usage: backends/schroot/test-package [OPTIONS] PACKAGE OUTPUTDIR

$@
EOF
}

base=$(readlink -f $(dirname $(readlink -f $0))/../..)
. $base/lib/environment.sh
. $base/lib/functions.sh

prepare_args

if [ $# -ne 2 ]; then
  usage
  exit 1
fi
package="$1"
outdir="$2"

tmpdir=$(mktemp -d)
cleanup() {
  if [ -d "$tmpdir" ]; then
    rm -rf "$tmpdir"
  fi
}
trap cleanup INT TERM EXIT

adt-run --gnupg-home="$debci_gnupg_dir" --user debci --output-dir "$outdir" "$package" --- adt-virt-schroot "${debci_chroot_name}"
