#!/bin/sh

set -eu

usage() {
  cat <<EOF
usage: backends/schroot/test-package [OPTIONS] PACKAGE OUTPUTDIR

$@
EOF
}

base=$(readlink -f $(dirname $(readlink -f $0))/../..)
. $base/lib/environment.sh
. $base/lib/functions.sh

prepare_args

if [ $# -ne 2 ]; then
  usage
  exit 1
fi
package="$1"
outdir="$2"

session_id="${debci_chroot_name}-$(basename "$package")"

rc=0
autopkgtest --user debci --output-dir "$outdir" --apt-upgrade "$package" -- schroot --session-id="${session_id}" "${debci_chroot_name}" || rc=$?
echo $rc > "$outdir/exitcode"
exit $rc
