#!/bin/sh

set -e

if [ "$1" = configure ] && [ -z "$2" ]; then
  # build testbed immediately on first install
  echo "Building testbeds in background ..."
  debci update-worker --quiet &

  if [ -d /run/systemd/system ]; then
    # enable && start first instance
    systemctl enable debci-worker@1.service

    # tell systemd to reload
    systemctl --system daemon-reload >/dev/null || true
  fi
  deb-systemd-invoke start  debci-worker@1.service
fi

##DEBHELPER##
