#!/bin/sh

cat <<EOF
var/lib/debci/data                           usr/share/debci/data
var/lib/debci/chroots                        usr/share/debci/chroots
var/lib/debci/gnupg                          usr/share/debci/gnupg
etc/debci                                    usr/share/debci/config
EOF

find bin/ -type f -executable | sed -e 's#bin/\(.*\)#usr/share/debci/bin/\1 usr/bin/\1#'
