#!/bin/sh
# postinst script for dep8

set -e

setup_system() {
    if [ ! -d /var/lib/dep8 ]; then
        mkdir /var/lib/dep8
    fi

    if [ ! -d /var/lib/dep8/data ]; then
        mkdir /var/lib/dep8/data
    fi

    chgrp dep8 /var/lib/dep8/data 2>/dev/null ||
        {
            addgroup --system dep8
            chgrp dep8 /var/lib/dep8/data
        }
    chown dep8 /var/lib/dep8/data 2>/dev/null ||
        {
            adduser --system --home /usr/share/dep8 --shell /bin/sh --no-create-home --disabled-password --ingroup dep8 dep8
            chown dep8 /var/lib/dep8/data
        }

    if [ ! -d /var/lib/dep8/chroots ]; then
        mkdir /var/lib/dep8/chroots
    fi

    if [ ! -d /var/lib/dep8/gnupg ]; then
        mkdir /var/lib/dep8/gnupg
        chown dep8:dep8 /var/lib/dep8/gnupg
    fi
}

case "$1" in
    configure)
        setup_system
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
