#!/bin/sh
# postinst script for debci

set -eu

setup_system() {
    if [ ! -d /var/lib/debci ]; then
        mkdir /var/lib/debci
    fi

    if [ ! -d /var/lib/debci/data ]; then
        mkdir /var/lib/debci/data
    fi

    chgrp debci /var/lib/debci/data 2>/dev/null ||
        {
            addgroup --system debci
            chgrp debci /var/lib/debci/data
        }
    chown debci /var/lib/debci/data 2>/dev/null ||
        {
            adduser --system --home /usr/share/debci --shell /bin/sh --no-create-home --disabled-password --ingroup debci debci
            chown debci /var/lib/debci/data
        }

    if [ ! -d /var/lib/debci/chroots ]; then
        mkdir /var/lib/debci/chroots
    fi

    if [ ! -d /var/lib/debci/gnupg ]; then
        mkdir /var/lib/debci/gnupg
        chown debci:debci /var/lib/debci/gnupg
    fi
}

case "$1" in
    configure)
        setup_system
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
