#!/bin/sh

set -eu

usage() {
  cat <<EOF
usage: backends/lxc/test-package [OPTIONS] PACKAGE OUTPUTDIR [EXTRA-AUTOPKGTEST-ARGS]

$@
EOF
}

base=$(readlink -f $(dirname $(readlink -f $0))/../..)
. $base/lib/environment.sh
. $base/lib/functions.sh

prepare_args

if [ $# -lt 2 ]; then
  usage
  exit 1
fi
package="$1"
outdir="$2"
shift
shift

debci-autopkgtest "$outdir" "$package" "$@" -- null
