#!/bin/sh

set -eu

usage() {
  cat <<EOF
usage: backends/lxc/test-package [OPTIONS] PACKAGE OUTPUTDIR

$@
EOF
}

base=$(readlink -f $(dirname $(readlink -f $0))/../..)
. $base/lib/environment.sh
. $base/lib/functions.sh

prepare_args

if [ $# -ne 2 ]; then
  usage
  exit 1
fi
package="$1"
outdir="$2"

rc=0
autopkgtest --output-dir "$outdir" "$package" -- null || rc=$?
echo $rc > "$outdir/exitcode"
exit $rc
