#!/usr/bin/ruby

require 'json'

class Blame
  def data
    @data ||= []
  end
end

class BlameCreator < Blame
  def <<(line)
    data << line
  end
end

class BlameUpdater < Blame
  def initialize(*pkgs)
    @pkgs = pkgs
  end
  def <<(line)
    pkg, version = line.split
    if @pkgs.include?(pkg)
      data << line
    end
  end
end

if ARGV.length == 0
  puts "usage: blame DIFF [pkg1 pkg2 ... pkgN]"
  exit 1
end

diff = ARGV.shift
if ARGV.length == 0
  blame = BlameCreator.new
else
  blame = BlameUpdater.new(*ARGV)
end

File.open(diff).lines.each do |line|
  if line =~ /^\+/ && line !~ /^\+\+\+/
    blame << line.strip.gsub(/\+/, '')
  end
end

puts JSON.dump(blame.data)
