#!/bin/sh

if [ "$(whoami)" != root ]; then
  echo "This script must be run as root"
  exit 1
fi

base=$(dirname $0)/..

# default configuration
concurrency=$(($(nproc) - 1))
user=$(stat -c %U "${base}/data")

if [ -r /etc/default/dep8runner ]; then
  . /etc/default/dep8runner
fi

cd $base

./scripts/setup > /dev/null

su "$user" -c "./scripts/process-all-packages -j $concurrency"
