#!/bin/sh

set -e

if [ "$(whoami)" != root ]; then
  echo "This script must be run as root"
  exit 1
fi

export LANG=C
export LC_ALL=C

script=$(readlink -f $0)
base=$(readlink -f $(dirname $script)/..)

# default configuration
concurrency=$(($(nproc) - 1))
if [ "$concurrency" -lt 1 ]; then
  concurrency=1
fi
data_dir=$(readlink -f ${base}/data)
user=$(stat -c %U "${data_dir}")

if [ -r /etc/default/dep8runner ]; then
  . /etc/default/dep8runner
fi

cd $base

log() {
  logger -t dep8 -i "$@"
}

run() {
  log "Starting setup phase"
  ./scripts/setup > /dev/null
  log "Finished setup phase"

  log "start processing of all packages"
  su "$user" -c "./scripts/process-all-packages -j $concurrency"
  log "finished processing of all packages"
}


(
  flock -n 9 || exit 0
  run
) 9>/var/lock/dep8.lock

