#!/bin/sh

set -e

base=$(readlink -f $(dirname $(readlink -f $0))/..)
. $base/lib/environment.sh

generate_index() {
  local prefix=""
  echo "["
  for pkg in $(find "${dep8_packages_dir}" -name latest.json | sort); do
    if [ -n "$prefix" ]; then
      echo "$prefix"
    fi
    cat $pkg
    prefix=","
  done
  echo "]"
}

generate_status_entry() {
  local duration="$1"
  pass=$(grep -l '"status":\s*"pass",' ${dep8_packages_dir}/*/*/latest.json | wc -l)
  fail=$(grep -l '"status":\s*"fail",' ${dep8_packages_dir}/*/*/latest.json | wc -l)
  total=$(($pass + $fail))
  date="$(date +%Y-%m-%dT%H:%M:%S)"
  mkdir -p "${dep8_status_dir}"
  cat > "${dep8_status_dir}/${date}.json" <<EOF
{
  "date": "$date",
  "duration": ${duration},
  "pass": $pass,
  "fail": $fail,
  "total": $total
}
EOF
  ln -sf "status/${date}.json" "${dep8_data_dir}/status.json"
}

generate_history() {
  local prefix=""
  echo "["
  for entry in $(find "${dep8_status_dir}" -name '*.json' -and -not -name history.json | sort); do
    if [ -n "$prefix" ]; then
      echo "$prefix"
    fi
    cat $entry
    prefix=","
  done
  echo "]"
}

generate_status_entry "$@"
generate_history > "${dep8_status_dir}/history.json"

generate_index > "${dep8_data_dir}/packages.json"

