#!/bin/sh

set -e

data_root="$(pwd)/data"
packages_root="${data_root}/packages"
status_root="${data_root}/status"

generate_index() {
  local prefix=""
  echo "["
  for pkg in $(find "${packages_root}" -name latest.json | sort); do
    if [ -n "$prefix" ]; then
      echo "$prefix"
    fi
    cat $pkg
    prefix=","
  done
  echo "]"
}

generate_status_entry() {
  pass=$(grep -l '"status":\s*"pass",' ${packages_root}/*/*/latest.json | wc -l)
  fail=$(grep -l '"status":\s*"fail",' ${packages_root}/*/*/latest.json | wc -l)
  total=$(($pass + $fail))
  date="$(date --rfc-3339=date)"
  if [ -f "${status_root}/${date}.json" ]; then
    return
  fi
  mkdir -p "${status_root}"
  cat > "${status_root}/${date}.json" <<EOF
{
  "date": "$date",
  "pass": $pass,
  "fail": $fail,
  "total": $total
}
EOF
  ln -sf "status/${date}.json" "${data_root}/status.json"
}

generate_history() {
  local prefix=""
  echo "["
  for entry in $(find "${status_root}" -name '*.json' -and -not -name history.json | sort); do
    if [ -n "$prefix" ]; then
      echo "$prefix"
    fi
    cat $entry
    prefix=","
  done
  echo "]"
}

generate_status_entry
generate_history > "${status_root}/history.json"

generate_index > "${data_root}/packages.json"

