#!/bin/sh

set -e

data_root=$(pwd)/data
packages_root=${data_root}/packages

generate_index() {
  local prefix=""
  echo "["
  for pkg in $(find "${packages_root}" -name latest.json | sort); do
    if [ -n "$prefix" ]; then
      echo "$prefix"
    fi
    cat $pkg
    prefix=","
  done
  echo "]"
}

generate_index > "${data_root}/packages.json"

