#!/bin/sh

set -e

base=$(readlink -f $(dirname $(readlink -f $0))/..)
. $base/lib/environment.sh
. $base/lib/functions.sh

list_packages() {
  grep_sources -n -s Package -F Testsuite -X autopkgtest | sort | uniq
}

whitelist="${debci_config_dir}/whitelist"
if [ -f "${whitelist}" ]; then
  for pkg in $(list_packages); do
    if grep -q "^${pkg}\$" "${whitelist}"; then
      echo "${pkg}"
    fi
  done
else
  list_packages
fi
