#!/bin/sh

set -e

base=$(readlink -f $(dirname $(readlink -f $0))/..)
. $base/lib/environment.sh
. $base/lib/functions.sh

date=$(date --rfc-3339=date)

global_tmp_dir=$(mktemp -d)
cleanup() {
  if [ -d "$global_tmp_dir" ]; then
    rm -rf "$global_tmp_dir"
  fi
}
trap cleanup INT TERM EXIT

one_month_ago="${global_tmp_dir}/one_month_ago"
touch -d '1 month ago' "${one_month_ago}"

process_package() {
  pkg="$1"

  # setup tmp dir
  tmp_dir="$global_tmp_dir/$pkg"
  mkdir "$tmp_dir"

  # setup status "DB"
  status_dir=$(status_dir_for_package "$pkg")
  mkdir -p "$status_dir"

  # setup log
  log_file="${status_dir}/${date}.log"

  if ! already_processed; then
    if [ -t 1 ]; then
      # stdout is a tty, show the output and also send it to the log file
      do_process_package "$pkg" 2>&1 | tee "$log_file"
    else
      # running on background, just send everything to the log file
      do_process_package "$pkg" > "$log_file" 2>&1
    fi
    if [ -s "$log_file" ]; then
      ln -sf "${date}.log" "${status_dir}/latest.log"
    fi
  fi
}

already_processed() {
  [ -f "$status_dir/${date}.json" ]
}

do_process_package() {
  pkg="$1"
  if needs_processing $pkg; then
    banner "System information"
    echo "Package versions:"
    dpkg-query --show debci autopkgtest | indent
    echo "Backend: $debci_backend"

    banner "Started: $(date -R)"

    start_time=$(date +%s)

    set +e
    test-package "$pkg"
    exit_status=$?
    set -e

    # ref: adt-run(1)
    case "$exit_status" in
      0)
        status=pass
        message='All tests passed'
        ;;
      2)
        status=pass
        message='Tests passed, but at least one test skipped'
        ;;
      4)
        status=fail
        message='Tests failed'
        ;;
      6)
        status=fail
        message='Tests failed, and at least one test skipped'
        ;;
      *)
        status=tmpfail
        message='Could not run tests due to a temporary failure'
        ;;
    esac
    finish_time=$(date +%s)
    duration=$(($finish_time - $start_time))

    record_status "$pkg" $status "$duration" "$message"

    banner "Finished: $(date -R)"
  fi
}

needs_processing() {
  check_dependencies "$pkg" > "$tmp_dir/dependencies.txt"

  run=1

  if [ -n "$cmdline_force" ]; then
    run=0
    banner "Forced test run for $pkg"
  else
    if [ -f "${status_dir}/latest.json" -a "${status_dir}/latest.json" -ot "${one_month_ago}" ]; then
      run=0
      banner 'Forced test run after 1 month without one'
    fi
  fi

  if [ -f "$status_dir/dependencies.txt" ]; then
    if diff -u --label last-run/dependencies.txt "$status_dir/dependencies.txt" --label current-run/dependencies.txt "$tmp_dir/dependencies.txt" > "$tmp_dir/dependencies.diff"; then
      # don't signal need to run test. Tests will only run if any of the above
      # conditions match
      true
    else
      run=0
      banner "Change in dependency chain for $pkg since last test run"
      cat "$tmp_dir/dependencies.diff"
    fi
  else
    run=0
    banner "First test run for $pkg"
  fi

  if [ "$run" -eq 0 ]; then
    cp "$tmp_dir/dependencies.txt" "${status_dir}/dependencies.txt"
    banner "Full dependency chain for $pkg at the moment"
    cat "$status_dir/dependencies.txt"
  fi

  return $run
}

check_dependencies() {
  pkg="$1"
  binaries=$(list_binaries "$pkg")
  {
    if ! schroot -d / -c "$debci_chroot_name" -u root -- apt-get install --quiet --assume-yes --simulate $binaries 2>&1; then
      for binary in $binaries; do
        schroot -d / -c "$debci_chroot_name" -u root -- apt-get -q -y --simulate  install $binary 2>&1
      done
    fi
  } | \
    awk '{ if ($1 == "Inst") { sub("^.", "", $3); print($2, $3) } }' | \
    sort | uniq
}

record_status() {
  pkg="$1"
  status="$2"
  duration="$3"
  message="$4"
  version=$(check_version "$pkg")

  hours=$(( $duration / 3600 ))
  minutes=$(( ($duration % 3600) / 60 ))
  seconds=$(( $duration - ($hours * 3600) - ($minutes * 60) ))
  duration_human="${hours}h ${minutes}m ${seconds}s"
  banner "Status: $status ($message); duration: ${duration_human}"

  # latest entry
  cat > "$status_dir/${date}.json" <<EOF
{
  "package": "${pkg}",
  "version": "${version}",
  "date": "${date}",
  "status": "${status}",
  "duration_seconds": "${duration}",
  "duration_human": "${duration_human}",
  "message": "${message}"
}
EOF
  ln -sf "${date}.json" "$status_dir/latest.json"

  # TODO cleanup old entries (?)

  # history
  history_file="$tmp_dir/history.json"
  echo '[' > "$history_file"
  sep=''
  for entry in $(find "$status_dir" -name '*.json' -and -not -name latest.json -and -not -name history.json | sort -r); do
    if [ -n "$sep" ]; then
      echo "$sep" >> "$history_file"
    fi
    sep=,
    cat $entry >> "$history_file"
  done
  echo ']' >> "$history_file"
  cp "$history_file" "$status_dir/history.json"
}

TEMP=`getopt -o f --long force -- "$@"`

if [ $? != 0 ]; then
  exit 1
fi

eval set -- "$TEMP"

# defaults
cmdline_force=''

while true; do
  case "$1" in
    -f|--force)
      shift
      cmdline_force="yes"
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "Internall error ($1)!"
      exit 1
      ;;
  esac
done

if [ $# -eq 1 ]; then
  process_package "$1"
else
  echo "usage: $0 [OPTIONS] PACKAGE"
  exit 1
fi
