#!/bin/sh

if [ $(whoami) != root ]; then
  echo "This script mus be run as root"
  exit 1
fi


suite='unstable' # FIXME
data_root=$(pwd)/data
chroot_root=${data_root}/chroots

create_chroot() {
  local suite="$1"
  local path="$2"

  echo "Creating $suite chroot (may take a while)"

  # detect a local apt-cacher-ng cache running.
  # 10.0.2.2 = default IP assigned to host system as seen from a kvm/virtualbox
  # virtual machine
  mirror=
  for ip in 127.0.0.1 10.0.2.2; do
    if nc -z -w 1 $ip 3142; then
      mirror=http://$ip:3142/debian
    fi
  done

  debootstrap "$suite" "$path" $mirror

  # do not download translations
  echo 'Acquire::Languages "none";' > "${path}/etc/apt/apt.conf.d/99translations"

  # add APT Source URIs
  sed -e 's/^deb\s/deb-src /' "${path}/etc/apt/sources.list" > "${path}/etc/apt/sources.list.d/sources.list"

  chroot "$path" apt-get update

  echo 'debconf debconf/frontend select noninteractive' | chroot "$path" debconf-set-selections
}

update_chroot() {
  local chroot_path="$1"

  echo "Updating $chroot_path (may take a while)"

  chroot "$chroot_path" apt-get update
  DEBIAN_FRONTEND=noninteractive chroot "$chroot_path" apt-get dist-upgrade -q -y
}

setup_schroot() {
  local suite="$1"
  local chroot_name="$2"
  local chroot_path="$3"

  local data_dir=$(readlink -f ${data_root})
  local user=$(stat -c %U "${data_dir}")
  if [ -z "$user" ]; then
    user=dep8
  fi

  cat > /etc/schroot/chroot.d/"${chroot_name}" <<EOF
[$chroot_name]
type=directory
description=DEP-8 $suite chroot
directory=${chroot_path}
users=$user
groups=$user
root-users=$user
source-root-users=$user
root-groups=root
union-type=aufs
EOF
}

setup_suite() {
  local suite="$1"

  # create chroot directory
  if [ ! -d "${chroot_root}" ]; then
    mkdir "${chroot_root}"
  fi

  chroot_name="dep8-${suite}"
  chroot_path="${chroot_root}/${suite}"
  if schroot --list --all | grep -q "^source:dep8-$suite\$"; then
    echo "Suite ${suite} already set up, skipping"
  else
    setup_schroot "$suite" "$chroot_name" "$chroot_path"
  fi

  local actual_chroot_path=$(schroot --config --chroot "$chroot_name" | grep '^directory=' | cut -d = -f 2)

  if [ -d "${actual_chroot_path}" ]; then
    update_chroot "$actual_chroot_path"
  else
    if [ "$actual_chroot_path" = "${chroot_path}" ]; then
      create_chroot "$suite" "$chroot_path"
    else
      echo "Chroot ${chroot_name} does not exit in custom location ${actual_chroot_path}. Please create it first."
    fi
  fi
}

# FIXME turn this into a loop when more than one suite is supported
setup_suite "$suite"

