#!/bin/sh

set -e

base=$(readlink -f $(dirname $(readlink -f $0))/..)
. $base/lib/environment.sh


if [ $(whoami) != root ]; then
  echo "This script must be run as root"
  exit 1
fi

create_chroot() {
  echo "Creating $debci_suite chroot (may take a while)"

  # detect a local apt-cacher-ng cache running.
  # 10.0.2.2 = default IP assigned to host system as seen from a kvm/virtualbox
  # virtual machine
  local mirror=
  for ip in 127.0.0.1 10.0.2.2; do
    if nc -z -w 1 $ip 3142; then
      mirror=http://$ip:3142/debian
    fi
  done

  debootstrap "$debci_suite" "$debci_chroot_path" $mirror

  # do not download translations
  echo 'Acquire::Languages "none";' > "${debci_chroot_path}/etc/apt/apt.conf.d/99translations"

  # add APT Source URIs
  sed -e 's/^deb\s/deb-src /' "${debci_chroot_path}/etc/apt/sources.list" > "${debci_chroot_path}/etc/apt/sources.list.d/sources.list"

  chroot "$debci_chroot_path" apt-get update

  echo 'debconf debconf/frontend select noninteractive' | chroot "$debci_chroot_path" debconf-set-selections
}

update_chroot() {
  local chroot_path="$1"

  echo "Updating $chroot_path (may take a while)"

  chroot "$chroot_path" apt-get update
  DEBIAN_FRONTEND=noninteractive chroot "$chroot_path" apt-get dist-upgrade -q -y
}

setup_schroot() {
  local data_dir=$(readlink -f ${debci_data_basedir})
  local user=$(stat -c %U "${data_dir}")
  if [ -z "$user" ]; then
    user=debci
  fi

  cat > /etc/schroot/chroot.d/"${debci_chroot_name}" <<EOF
[$debci_chroot_name]
type=directory
description=debci $debci_suite/$debci_arch chroot
directory=${debci_chroot_path}
users=$user
groups=$user
root-users=$user
source-root-users=$user
root-groups=root
union-type=aufs
EOF
}

setup_suite() {
  # create chroot directory
  if [ ! -d "${debci_chroots_dir}" ]; then
    mkdir "${debci_chroots_dir}"
  fi

  if schroot --list --all | grep -q "^source:${debci_chroot_name}\$"; then
    echo "schroot setup for ${debci_suite} already done, skipping"
  else
    setup_schroot
  fi

  local actual_chroot_path=$(schroot --config --chroot "$debci_chroot_name" | grep '^directory=' | cut -d = -f 2)

  if [ -d "${actual_chroot_path}" ]; then
    update_chroot "$actual_chroot_path"
  else
    if [ "$actual_chroot_path" = "${debci_chroot_path}" ]; then
      create_chroot
    else
      echo "Chroot ${debci_chroot_name} does not exit in custom location ${actual_chroot_path}. Please create it first."
      exit 1
    fi
  fi
}

setup_suite
