#!/bin/sh

set -e

if [ $# -ne 1 ]; then
  echo "usage: $0 PACKAGE"
  exit 1
fi
package="$1"

tmpdir=$(mktemp -d)
cleanup() {
  if [ -d "$tmpdir" ]; then
    rm -rf "$tmpdir"
  fi
}
trap cleanup INT TERM EXIT

suite=unstable # FIXME this should be a parameter (?)

cd $tmpdir
schroot --chroot dep8-$suite -- apt-get source --download-only $package
dpkg-source -x *.dsc
source=$(find . -mindepth 1 -maxdepth 1 -type d)
cd "$source"
adt-run --built-tree . --- adt-virt-schroot "$suite"
