#!/bin/sh

set -e

base=$(readlink -f $(dirname $(readlink -f $0))/..)
. $base/lib/environment.sh

if [ $# -ne 1 ]; then
  echo "usage: $0 PACKAGE"
  exit 1
fi
package="$1"

tmpdir=$(mktemp -d)
cleanup() {
  if [ -d "$tmpdir" ]; then
    rm -rf "$tmpdir"
  fi
}
trap cleanup INT TERM EXIT

cd $tmpdir
schroot --chroot "${dep8_chroot_name}" -- apt-get source --download-only $package
dpkg-source -x *.dsc
source=$(find . -mindepth 1 -maxdepth 1 -type d)
cd "$source"
adt-run --built-tree . --- adt-virt-schroot "${dep8_chroot_name}"
