#!/bin/sh

export DEBIAN_FRONTEND=noninteractive

apt-get install -qy lighttpd

lighttpd-enable-mod simple-vhost
mkdir -p /srv/localhost
ln -sf /usr/share/debci/public /src/localhost/htdocs

service lighttpd restart

echo '---------------------------------'
echo "debci packages are NOT installed!"
echo '---------------------------------'
