#!/bin/sh

set -eu

usage() {
  cat <<EOF
usage: backends/qemu/test-package [OPTIONS] PACKAGE OUTPUTDIR [EXTRA-AUTOPKGTEST-ARGS]

$@
EOF
}

backend=$(readlink -f $(dirname "$0"))
. "$backend/environment.sh"

debci-autopkgtest --user debci "$@" \
  -- qemu "$image"
