#!/bin/sh

set -eu

usage() {
  cat <<EOF
usage: backends/qemu/test-package [OPTIONS] PACKAGE OUTPUTDIR [EXTRA-AUTOPKGTEST-ARGS]

$@
EOF
}

base=$(readlink -f $(dirname $(readlink -f $0))/../..)
. $base/lib/environment.sh
backend=$(readlink -f $(dirname "$0"))
. "$backend/environment.sh"

prepare_args

if [ $# -lt 2 ]; then
  usage
  exit 1
fi
package="$1"
outdir="$2"
shift
shift

debci-autopkgtest "$outdir" --user debci --apt-upgrade "$package" "$@" \
  -- qemu "$image"
